# Generated by Django 3.2.5 on 2021-07-24 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_commemtpost'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommemtPost',
            new_name='CommentPost',
        ),
    ]
