# Generated by Django 3.2.5 on 2021-07-28 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20210727_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentpost',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='commentpost',
            name='post',
        ),
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_follow',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'following'), name='unique_follow'),
        ),
        migrations.DeleteModel(
            name='CommentPost',
        ),
    ]
