# Generated by Django 3.2.5 on 2021-07-29 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20210728_0839'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['title'], 'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
    ]
