# Generated by Django 3.2.5 on 2021-07-29 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20210729_0651'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['id', 'title'], 'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
    ]
