# Generated by Django 3.2.5 on 2021-07-29 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_alter_group_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'ordering': ['following'], 'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
    ]
