# Generated by Django 3.2.5 on 2021-07-30 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_auto_20210730_0758'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'ordering': ['id', 'following']},
        ),
    ]
