# Generated by Django 3.2.5 on 2021-07-30 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_alter_follow_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'ordering': ['-id', 'following']},
        ),
    ]
